### ISSUE TITLE
Add Dashicons to Left Menu With Mobile Support

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/Commons-Toolbar#1]
Home: content: "\f319";
Support: content: "\f468";
Blog Requests: content: "\f125";
Developments: content: "\f308";

**Comment by r-a-y** [comment]
Do you mean you want four additional icons in the mobile nav?  Wouldn't that make the adminbar cluttered?  Especially for an admin of a blog?

**Comment by mrjarbenne** [comment]
It's a dropdown.

It's really only one additional icon.
